  main = ".open-next/worker.js"
  name = "okiro-studio-landing"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
  routes = [
  { pattern = "okirostudio.com", custom_domain = true }
  ]